global:
    secure: rsIi7zqeKvMh7G5Jxx8WdUZzp16uxoyunO3yWru/z2Cyllcr+ufTEgy+CZoOhLo9HPDE4mwr/c9Hp7zukuW7aBBrfaK5rPQ5+ZvlHZtWB6bTzJPfjCUuoXbsbh/GHu2cQYTY8WuqhugCchOwohAA3GQCgK+58pw8rZXj/LBFFqM=
language: node_js
node_js:
- '0.10'
install:
- npm install wintersmith -g
- gem install s3_website
- cd blog
- npm install
script:
- npm test
- wintersmith build
- mv build ../build
- cd ../
- s3_website push --site build  
